-- MySQL Script generated by MySQL Workbench
-- Thu Mar  5 15:59:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Devs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Devs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Devs` (
  `idDevs` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDevs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publishers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Publishers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Publishers` (
  `idPublishers` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPublishers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Processors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Processors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Processors` (
  `idProcessors` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProcessors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grafic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Grafic` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Grafic` (
  `idGrafic` INT NOT NULL,
  `Graficcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGrafic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Game` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `idGame` INT NOT NULL,
  `Game_Name` VARCHAR(60) NOT NULL,
  `Short_Description` VARCHAR(200) NOT NULL,
  `Developer` INT NOT NULL,
  `Publisher` INT NOT NULL,
  `Release` DATE NOT NULL,
  `Cover` BLOB NOT NULL,
  `Metascore` INT NULL,
  `Userscore` INT NULL,
  `FullDescription` VARCHAR(500) NULL,
  `FullDescription2` VARCHAR(400) NULL,
  `Processor` INT NULL,
  `RAM` VARCHAR(10) NULL,
  `Grafic` INT NULL,
  `Storage` VARCHAR(10) NULL,
  `Price` DECIMAL NOT NULL,
  PRIMARY KEY (`idGame`),
  INDEX `Dev_idx` (`Developer` ASC) VISIBLE,
  INDEX `Publ_idx` (`Publisher` ASC) VISIBLE,
  INDEX `Proc_idx` (`Processor` ASC) VISIBLE,
  INDEX `Graf_idx` (`Grafic` ASC) VISIBLE,
  CONSTRAINT `Dev`
    FOREIGN KEY (`Developer`)
    REFERENCES `mydb`.`Devs` (`idDevs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Publ`
    FOREIGN KEY (`Publisher`)
    REFERENCES `mydb`.`Publishers` (`idPublishers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Proc`
    FOREIGN KEY (`Processor`)
    REFERENCES `mydb`.`Processors` (`idProcessors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Graf`
    FOREIGN KEY (`Grafic`)
    REFERENCES `mydb`.`Grafic` (`idGrafic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CategoriesOfGames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CategoriesOfGames` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CategoriesOfGames` (
  `idGameTypes` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Icon` BLOB NOT NULL,
  PRIMARY KEY (`idGameTypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Photos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Photos` (
  `idPhotos` INT NOT NULL,
  `Game` INT NOT NULL,
  `Photo` BLOB NOT NULL,
  PRIMARY KEY (`idPhotos`),
  INDEX `Game_idx` (`Game` ASC) VISIBLE,
  CONSTRAINT `GamePh`
    FOREIGN KEY (`Game`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VRDevs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VRDevs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VRDevs` (
  `idVRDevs` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVRDevs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VR` (
  `idVR` INT NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Release Date` DATE NOT NULL,
  `Weight` DECIMAL NULL,
  `Price` DECIMAL NOT NULL,
  `Developer` INT NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idVR`),
  INDEX `VRDevelop_idx` (`Developer` ASC) VISIBLE,
  CONSTRAINT `VRDevelop`
    FOREIGN KEY (`Developer`)
    REFERENCES `mydb`.`VRDevs` (`idVRDevs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Controller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Controller` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Controller` (
  `idController` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Developer` INT NOT NULL,
  `Price` DECIMAL NOT NULL,
  PRIMARY KEY (`idController`),
  INDEX `VRDevForC_idx` (`Developer` ASC) VISIBLE,
  CONSTRAINT `VRDevForC`
    FOREIGN KEY (`Developer`)
    REFERENCES `mydb`.`VRDevs` (`idVRDevs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BaseStation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BaseStation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BaseStation` (
  `idBaseStation` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Developer` INT NOT NULL,
  `Price` DECIMAL NOT NULL,
  PRIMARY KEY (`idBaseStation`),
  INDEX `VrDevForBS_idx` (`Developer` ASC) VISIBLE,
  CONSTRAINT `VrDevForBS`
    FOREIGN KEY (`Developer`)
    REFERENCES `mydb`.`VRDevs` (`idVRDevs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`First-Page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`First-Page` ;

CREATE TABLE IF NOT EXISTS `mydb`.`First-Page` (
  `idFirst-Page` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Desc` VARCHAR(200) NULL,
  `Img1` BLOB NOT NULL,
  `Img2` BLOB NOT NULL,
  `ItemCat` VARCHAR(30) NOT NULL,
  `idItem` VARCHAR(45) NULL,
  PRIMARY KEY (`idFirst-Page`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Games-Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Games-Categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Games-Categories` (
  `idGC` INT NOT NULL,
  `Game` INT NOT NULL,
  `Category` INT NOT NULL,
  PRIMARY KEY (`idGC`),
  INDEX `Game_idx` (`Game` ASC) VISIBLE,
  INDEX `Category_idx` (`Category` ASC) VISIBLE,
  CONSTRAINT `GameCat`
    FOREIGN KEY (`Game`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CategoryCat`
    FOREIGN KEY (`Category`)
    REFERENCES `mydb`.`CategoriesOfGames` (`idGameTypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CategoriesForFirstPage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CategoriesForFirstPage` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CategoriesForFirstPage` (
  `idCategoriesForFirstPage` INT NOT NULL,
  `idCat` INT NOT NULL,
  PRIMARY KEY (`idCategoriesForFirstPage`),
  INDEX `FPCat_idx` (`idCat` ASC) VISIBLE,
  CONSTRAINT `FPCat`
    FOREIGN KEY (`idCat`)
    REFERENCES `mydb`.`CategoriesOfGames` (`idGameTypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
